_Please make sure that this is a build/installation issue. As per ourGitHub
Policy, we only address code/doc bugs, performance issues, feature requests
and build/installation issues on GitHub. tag:build_template_
**System information**
  * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOs 6.10 Linux: 2.6.32-754.2.1.el6.x86_64
  * TensorFlow installed from (source or binary): Conda install
  * TensorFlow version: 1.14.0
  * Python version: 3.7.5
  * Installed using virtualenv? pip? conda?: Conda
  * GCC/Compiler version (if compiling from source): c++ 4.9.2
  * CUDA/cuDNN version:
  * GPU model and memory:
**Describe the problem**  
Import error ImportError: /opt/gnu/gcc/lib64/libstdc++.so.6: version
`GLIBCXX_3.4.21' not found (required by
/home/atanteck/anaconda3/lib/python3.7/site-
packages/tensorflow/python/_pywrap_tensorflow_internal.so). Indicated file is
there at the path.
**Provide the exact sequence of commands / steps that you executed before
running into the problem**  
Import tensorflow
**Any other info / logs**
> > > import tensorflow  
>  Traceback (most recent call last):  
>  File "/home/atanteck/anaconda3/lib/python3.7/site-
> packages/tensorflow/python/pywrap_tensorflow.py", line 58, in  
>  from tensorflow.python.pywrap_tensorflow_internal import *  
>  File "/home/atanteck/anaconda3/lib/python3.7/site-
> packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in  
>  _pywrap_tensorflow_internal = swig_import_helper()  
>  File "/home/atanteck/anaconda3/lib/python3.7/site-
> packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in
> swig_import_helper  
>  _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname,
> description)  
>  File "/home/atanteck/anaconda3/lib/python3.7/imp.py", line 242, in
> load_module  
>  return load_dynamic(name, filename, file)  
>  File "/home/atanteck/anaconda3/lib/python3.7/imp.py", line 342, in
> load_dynamic  
>  return _load(spec)  
>  ImportError: /opt/gnu/gcc/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21'
> not found (required by /home/atanteck/anaconda3/lib/python3.7/site-
> packages/tensorflow/python/_pywrap_tensorflow_internal.so)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):  
File "", line 1, in  
File "/home/atanteck/anaconda3/lib/python3.7/site-packages/tensorflow/
**init**.py", line 34, in  
from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-
import  
File "/home/atanteck/anaconda3/lib/python3.7/site-packages/tensorflow/python/
**init**.py", line 49, in  
from tensorflow.python import pywrap_tensorflow  
File "/home/atanteck/anaconda3/lib/python3.7/site-
packages/tensorflow/python/pywrap_tensorflow.py", line 74, in  
raise ImportError(msg)  
ImportError: Traceback (most recent call last):  
File "/home/atanteck/anaconda3/lib/python3.7/site-
packages/tensorflow/python/pywrap_tensorflow.py", line 58, in  
from tensorflow.python.pywrap_tensorflow_internal import *  
File "/home/atanteck/anaconda3/lib/python3.7/site-
packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in  
_pywrap_tensorflow_internal = swig_import_helper()  
File "/home/atanteck/anaconda3/lib/python3.7/site-
packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in
swig_import_helper  
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname,
description)  
File "/home/atanteck/anaconda3/lib/python3.7/imp.py", line 242, in load_module  
return load_dynamic(name, filename, file)  
File "/home/atanteck/anaconda3/lib/python3.7/imp.py", line 342, in
load_dynamic  
return _load(spec)  
ImportError: /opt/gnu/gcc/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not
found (required by /home/atanteck/anaconda3/lib/python3.7/site-
packages/tensorflow/python/_pywrap_tensorflow_internal.so)
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors
for some common reasons and solutions. Include the entire stack trace  
above this error message when asking for help.