Why does catch return an object and not an error object?