# Checklist
  * I have verified that the issue exists against the `master` branch of Celery.
  * This has already been asked to the discussion group first.
  * I have read the relevant section in the  
contribution guide  
on reporting bugs.
  * I have checked the issues list  
for similar or identical bug reports.
  * I have checked the pull requests list  
for existing proposed fixes.
  * I have checked the commit log  
to find out if the bug was already fixed in the master branch.
  * I have included all related issues and possible duplicate issues  
in this issue (If there are none, check this box anyway).
## Mandatory Debugging Information
  * I have included the output of `celery -A proj report` in the issue.  
(if you are not able to do this, then at least specify the Celery  
version affected).
  * I have verified that the issue exists against the `master` branch of Celery.
  * I have included the contents of `pip freeze` in the issue.
  * I have included all the versions of all the external dependencies required  
to reproduce this bug.
## Related Issues and Possible Duplicates
#### Related Issues
  * None
#### Possible Duplicates
  * None
## Environment & Settings
**5.0.0** :
# Expected Behavior
I'm a new celery user, not quite sure if I should report this as a bug or
feature request and I'm not quite sure how to best fix this myself, so I hope
you'll bear with me :-)
Redis 6.0 or greater implements users in the form of ACL (see
https://redis.io/topics/acl), however, celery throws an WRONGPASS error when
using the following broker URL:
`redis://user:password@localhost:6379/0`
We would expect celery to connect to redis using the correct user:password
combination and not throw a password error. Older redis versions did not
implement ACL; looking at _params_from_url function on line 277 in
celery/backend/redis.py, it seems like celery currently only implements a
broker URL containing a password and no username, as indicated by line 278:
`scheme, host, port, _, password, path, query = _parse_url(url)`
I would expect celery to implement the user:password@host scheme, as well as
the current password@host scheme in order to correctly handle the ACL
introduced in redis >6.0
# Actual Behavior
Celery throws this error:
    [2020-10-18 02:35:54,748: ERROR/MainProcess] consumer: Cannot connect to redis://user:**@localhost:6379/0: WRONGPASS invalid username-password pair.
    Trying again in 18.00 seconds... (9/100)```