I setup o 2-node kubernetes cluster using docker containers, as described
here: https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/getting-
started-guides/docker-multinode.md
Now, I created a secret and a test pod:  
(using files from the branch 'release-1.1' and commit
'ac3f023ab28ed4f4c4f88a3fb518e90f4a8d4749')
    kubectl create -f docs/user-guide/secrets/secret.yaml
    kubectl create -f docs/user-guide/secrets/secret-pod.yaml
Both secret and pod are created:
    $ kubectl describe secret test-secret
    Name:           test-secret
    Namespace:      default
    Labels:         
    Annotations:    
    Type:   Opaque
    Data
    ====
    data-1: 9 bytes
    data-2: 11 bytes
    $ kubectl describe po/secret-test-pod
    Name:                           secret-test-pod
    Namespace:                      default
    Image(s):                       kubernetes/mounttest:0.1
    Node:                           127.0.0.1/127.0.0.1
    Start Time:                     Thu, 10 Dec 2015 16:20:49 +0100
    Labels:                         
    Status:                         Running
    Reason: 
    Message:
    IP:                             10.1.61.8
    Replication Controllers:        
    Containers:
      test-container:
        Container ID:       docker://82409e45ad6fcd73a8100a1b0767692d5e823cc3a14d8154644293d6b4c86854
        Image:              kubernetes/mounttest:0.1
        Image ID:           docker://b14127f747a0569e9ab96f0ee2de1b07630b7dbc16f8facf0b0adabd5848d41c
        State:              Running
          Started:          Thu, 10 Dec 2015 16:20:51 +0100
        Ready:              False
        Restart Count:      0
        Environment Variables:
    Conditions:
      Type          Status
      Ready         False 
    Volumes:
      secret-volume:
        Type:       Secret (a secret that should populate this volume)
        SecretName: test-secret
    Events:
      FirstSeen     LastSeen        Count   From                    SubobjectPath                           Reason          Message
      ─────────     ────────        ─────   ────                    ─────────────                           ──────          ───────
      9s            9s              1       {scheduler }                                                    Scheduled       Successfully assigned secret-test-pod to 127.0.0.1
      8s            8s              1       {kubelet 127.0.0.1}     implicitly required container POD       Pulled          Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
      8s            8s              1       {kubelet 127.0.0.1}     implicitly required container POD       Created         Created with docker id cb1290a496c8
      8s            8s              1       {kubelet 127.0.0.1}     implicitly required container POD       Started         Started with docker id cb1290a496c8
      8s            8s              1       {kubelet 127.0.0.1}                                             FailedSync      Error syncing pod, skipping: open /var/lib/docker/containers/cb1290a496c8d3721064573b27ddd0530c864462374ec0106b5a2cb25fdee916/resolv.conf: read-only file system
      7s            7s              1       {kubelet 127.0.0.1}     spec.containers{test-container}         Pulled          Container image "kubernetes/mounttest:0.1" already present on machine
      7s            7s              1       {kubelet 127.0.0.1}     spec.containers{test-container}         Created         Created with docker id 82409e45ad6f
      7s            7s              1       {kubelet 127.0.0.1}     spec.containers{test-container}         Started         Started with docker id 82409e45ad6f
but the secret directory inside the container is empty:
    $ kubectl logs secret-test-pod
    error reading file content for "/etc/secret-volume/data-1": open /etc/secret-volume/data-1: no such file or directory
This is tested on ubuntu 14.04.3 and docker "version 1.9.1, build a34a1d5"
with AUFS on ext4.
What does the "FailedSync Error" in the status of a pod mean? The kubelet's
log is also full of lines like:
    W1210 15:25:08.504876    8522 container_manager_linux.go:278] [ContainerManager] Failed to ensure state of "/docker-daemon": failed to move PID 20479 (in "/user/1000.user/14.session") to "/docker-daemon"
    I1210 15:25:09.337270    8522 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/5819740f39449d681e73c362cbdcef218454bc0e8ba4c442905069d803be0d13 with output du: cannot access '/var/lib/docker/aufs/diff/5819740f39449d681e73c362cbdcef218454bc0e8ba4c442905069d803be0d13': No such file or directory
     - exit status 1
    I1210 15:25:10.939578    8522 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/81c12f13a7a06c075b8aa1544c6e070f5c3fbcb0dfc4e75adb290a45804faf16 with output du: cannot access '/var/lib/docker/aufs/diff/81c12f13a7a06c075b8aa1544c6e070f5c3fbcb0dfc4e75adb290a45804faf16': No such file or directory
     - exit status 1
    I1210 15:25:10.940009    8522 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/1685f493d119093d3f1ef0a069e0936a8aa7f8708409a22c700faad351f75d08 with output du: cannot access '/var/lib/docker/aufs/diff/1685f493d119093d3f1ef0a069e0936a8aa7f8708409a22c700faad351f75d08': No such file or directory
     - exit status 1
    I1210 15:25:11.010029    8522 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/ffef039cd9b3194b33a59b609f8561166b9caea3ca28ed7c2632edfde3322f38 with output du: cannot access '/var/lib/docker/aufs/diff/ffef039cd9b3194b33a59b609f8561166b9caea3ca28ed7c2632edfde3322f38': No such file or directory
     - exit status 1
    I1210 15:25:13.054248    8522 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/b47debeea5b8943708b360b55f6152116189c1c7724ad71dfa1596dd2e8f4160 with output du: cannot access '/var/lib/docker/aufs/diff/b47debeea5b8943708b360b55f6152116189c1c7724ad71dfa1596dd2e8f4160': No such file or directory
     - exit status 1
    I1210 15:25:14.771897    8522 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/38add271c97d5c427f14433d65a124605a82c88d407f96654acc77dc4016e04b with output du: cannot access '/var/lib/docker/aufs/diff/38add271c97d5c427f14433d65a124605a82c88d407f96654acc77dc4016e04b': No such file or directory
     - exit status 1
    I1210 15:25:16.292393    8522 fsHandler.go:87] failed to collect filesystem stats - du command failed on /var/lib/docker/aufs/diff/3bce298fa4e90e4122eddcd0f9412b2f663f2dbea41dfd0257f6bcdb9fae4476 with output du: cannot access '/var/lib/docker/aufs/diff/3bce298fa4e90e4122eddcd0f9412b2f663f2dbea41dfd0257f6bcdb9fae4476': No such file or directory
     - exit status 1
but none of them is "error"