 _Please make sure that this is a build/installation issue. As per ourGitHub
Policy, we only address code/doc bugs, performance issues, feature requests
and build/installation issues on GitHub. tag:build_template_
**System information**
  * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 7
  * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
  * TensorFlow installed from (source or binary): installation from https://www.tensorflow.org/install/pip
  * TensorFlow version: 1.13
  * Python version: 3.6.8
  * Installed using virtualenv? pip? conda?: both pip, virtualenv
  * Bazel version (if compiling from source):no
  * GCC/Compiler version (if compiling from source): no
  * CUDA/cuDNN version: tried with all CUDA8, CUDA7.5,CUDA9
  * GPU model and memory:
**Describe the problem**  
I tried different version of python and tensorflow and check the script for
selecting CUDA version, it has the same error. Also I installed airflow but
desn't work!!!!!!  
**Provide the exact sequence of commands / steps that you executed before
running into the problem**  
Traceback (most recent call last):  
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-
packages\tensorflow\python\pywrap_t  
ensorflow.py", line 58, in  
from tensorflow.python.pywrap_tensorflow_internal import *  
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-
packages\tensorflow\python\pywrap_t  
ensorflow_internal.py", line 28, in  
_pywrap_tensorflow_internal = swig_import_helper()  
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-
packages\tensorflow\python\pywrap_t  
ensorflow_internal.py", line 24, in swig_import_helper  
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname,
description)  
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\imp.py", line
243, in load_module  
return load_dynamic(name, filename, file)  
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\imp.py", line
343, in load_dynamic  
return _load(spec)  
ImportError: DLL load failed with error code -1073741795
During handling of the above exception, another exception occurred:
Traceback (most recent call last):  
File "", line 1, in  
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-
packages\tensorflow_ _init_ _.py", l  
ine 24, in  
from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-
import  
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-
packages\tensorflow\python_ _init_ _  
.py", line 49, in  
from tensorflow.python import pywrap_tensorflow  
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-
packages\tensorflow\python\pywrap_t  
ensorflow.py", line 74, in  
raise ImportError(msg)  
ImportError: Traceback (most recent call last):  
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-
packages\tensorflow\python\pywrap_t  
ensorflow.py", line 58, in  
from tensorflow.python.pywrap_tensorflow_internal import *  
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-
packages\tensorflow\python\pywrap_t  
ensorflow_internal.py", line 28, in  
_pywrap_tensorflow_internal = swig_import_helper()  
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\site-
packages\tensorflow\python\pywrap_t  
ensorflow_internal.py", line 24, in swig_import_helper  
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname,
description)  
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\imp.py", line
243, in load_module  
return load_dynamic(name, filename, file)  
File "C:\Users\azak\AppData\Local\Programs\Python\Python36\lib\imp.py", line
343, in load_dynamic  
return _load(spec)  
ImportError: DLL load failed with error code -1073741795
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors
for some common reasons and solutions. Include the entire stack trace  
above this error message when asking for help.
**Any other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and
files should be attached.