**异常信息：**

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/tensorflow_gpu-0.12.1.dist-info'
```

**问题描述：**
在尝试使用 `pip` 安装或升级一个包时，系统报告了一个权限错误。具体来说，在创建目录 `/usr/local/lib/python2.7/dist-packages/tensorflow_gpu-0.12.1.dist-info` 时被拒绝访问。

**可能原因：**
- 当前用户没有足够的权限来写入目标路径。
- 目标文件夹可能存在只读属性或者已被其他程序锁定。

**建议解决方案：**
1. 尝试以超级用户身份运行命令（例如使用 `sudo pip install <package>`）。请注意这样做会将软件包安装到全局环境中，这可能会影响系统的稳定性。
2. 如果不想以管理员身份安装，可以考虑为当前用户设置一个虚拟环境，并在此环境下进行安装操作。这样既保证了安全性也避免了权限问题。
3. 检查指定路径是否具有适当的权限设置。如果必要的话，修改其权限使其可写。

请根据实际情况选择合适的解决方法。